# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: chester's blog
email: cd@pobox.com
author: Chester (Carlos Duarte do Nascimento)
simple_search: //duckduckgo.com
subscribe_rss: http://feeds.feedburner.com/chesterbr
#description: >- # this means to ignore newlines until "baseurl:"
#  technology, travel, comics, books, math, web, software and random thoughts
subtitle: >- # this means to ignore newlines until "baseurl:"
  technology, travel, comics, books, math, web, software and random thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chester.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chesterbr
github_username:  chesterbr

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

paginate: 10          # Posts per page on the blog index
recent_posts: 5       # Posts in the sidebar Recent Posts section
paginate_path: /page:num/  # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

excerpt_separator: <!--more-->

titlecase: true       # Converts page and post titles to titlecase

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
permalink: /archives/:year/:month/:title/

# Disqus Comments
disqus_short_name: chesterbr
disqus_show_comment_count: true

# Github repositories
github_user: chesterbr
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: chesterbr
twitter_tweet_button: false
twitter_follow_button: false

# Google Analytics
# google_analytics_tracking_id:

# Facebook Like
facebook_like: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll_admin:
  homepage: "posts"
